### ISSUE TITLE
Use Beacon API for supported browsers

### ISSUE THREAD

**Issue by nowarkdev** [nowtv/event-collector#17] opened 2015-07-15 13:39 UTC
We can use [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) in the [supported browsers](http://caniuse.com/#search=beacon).

-
Anuj & Pierre

**Comment by nowtv-web** [comment] 2015-07-15 13:46
Duplicate of #1 Covered in #13

**Closed by nowtv-web** 2015-07-15 13:46 UTC
